"""initial migration

Revision ID: 19569dd4f8c8
Revises: 
Create Date: 2026-05-13 01:03:26.847469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19569dd4f8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('backgroundColor', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isTask', sa.Boolean(), nullable=True),
    sa.Column('taskStatus', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_email', sa.String(length=120), nullable=False),
    sa.Column('addressee_email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('requester_email != addressee_email', name='no_self_friendship'),
    sa.ForeignKeyConstraint(['addressee_email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['requester_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_email', 'addressee_email', name='unique_friendship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
