"""Use Python enum for task status

Revision ID: 3fd5b4af6b44
Revises: 55b7d555f0c3
Create Date: 2026-05-05 15:28:23.450580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd5b4af6b44'
down_revision = '55b7d555f0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('taskStatus',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('taskStatus',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
