"""added isTask boolean column to Event


Revision ID: 63ba1aa43ce5
Revises: db5bcc08fa32
Create Date: 2026-05-04 22:04:58.135103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ba1aa43ce5'
down_revision = 'db5bcc08fa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isTask', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('isTask')

    # ### end Alembic commands ###
