"""added taskStatus string column to Event table

Revision ID: f0482bd5228c
Revises: 63ba1aa43ce5
Create Date: 2026-05-04 22:09:42.445135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0482bd5228c'
down_revision = '63ba1aa43ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskStatus', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('taskStatus')

    # ### end Alembic commands ###
